<h1>Script para evaluación de tamaños y tiempos<h1>

In [1]:
using NBInclude
using PyPlot
nbinclude("LinearGraphLearning.ipynb")
nbinclude("AuxFunctions.ipynb")
nbinclude("GraphLearning.ipynb")

learnl2Error (generic function with 1 method)

In [7]:
#Seed para las pruebas
TT = STDOUT # save original STDOUT stream
redirect_stdout()
srand(1236)
redirect_stdout(TT) # restore STDOUT

Base.PipeEndpoint(Base.Libc.WindowsRawSocket(Ptr{Void} @0x0000000000000280) open, 0 bytes waiting)

<h2>Grafos usados<h2>

<h5>n =250<h5>

In [8]:
grafo250obs1 = Array{Any}(1)
grafo250obs1[1]=erdosgraph([0.6,0.6],0.05,[125,125],250)


250×250 Array{Float64,2}:
 0.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.

In [ ]:

grafo250obs3 = Array{Any}(3)
grafo250obs3[1]=erdosgraph([0.6,0.6],0.05,[125,125],250)
grafo250obs3[2]=erdosgraph([0.6,0.6],0.05,[125,125],250)
grafo250obs3[3]=erdosgraph([0.6,0.6],0.05,[125,125],250)


In [ ]:
grafo250obs7 = Array{Any}(7)
grafo250obs7[1]=erdosgraph([0.6,0.6],0.05,[125,125],250)
grafo250obs7[2]=erdosgraph([0.6,0.6],0.05,[125,125],250)
grafo250obs7[3]=erdosgraph([0.6,0.6],0.05,[125,125],250)
grafo250obs7[4]=erdosgraph([0.6,0.6],0.05,[125,125],250)
grafo250obs7[5]=erdosgraph([0.6,0.6],0.05,[125,125],250)
grafo250obs7[6]=erdosgraph([0.6,0.6],0.05,[125,125],250)
grafo250obs7[7]=erdosgraph([0.6,0.6],0.05,[125,125],250)


<h5>n =500<h5>

In [ ]:
grafo500obs1 = Array{Any}(1)
grafo500obs1[1]=erdosgraph([0.6,0.6],0.05,[250,250],500)

In [ ]:

grafo500obs3 = Array{Any}(3)
grafo500obs3[1]=erdosgraph([0.6,0.6],0.05,[250,250],500)
grafo500obs3[2]=erdosgraph([0.6,0.6],0.05,[250,250],500)
grafo500obs3[3]=erdosgraph([0.6,0.6],0.05,[250,250],500)

In [3]:
grafo500obs7 = Array{Any}(7)
grafo500obs7[1]=erdosgraph([0.6,0.6],0.05,[250,250],500)
grafo500obs7[2]=erdosgraph([0.6,0.6],0.05,[250,250],500)
grafo500obs7[3]=erdosgraph([0.6,0.6],0.05,[250,250],500)
grafo500obs7[4]=erdosgraph([0.6,0.6],0.05,[250,250],500)
grafo500obs7[5]=erdosgraph([0.6,0.6],0.05,[250,250],500)
grafo500obs7[6]=erdosgraph([0.6,0.6],0.05,[250,250],500)
grafo500obs7[7]=erdosgraph([0.6,0.6],0.05,[250,250],500)


500×500 Array{Float64,2}:
 0.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  …  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  1.0  1.0  1.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.

<h2>Evaluación de recuperación lineal de grafos<h2>

<h5>n=250<h5>

In [ ]:
#30 s
tic()
resultado1lineal=learnLinearGraph([1],0.5,grafo250obs1,250)
toc()

In [ ]:
#t=48 s
tic()
resultado2lineal=learnLinearGraph([1/3,1/3,1/3],0.5,grafo250obs3,250)
toc()

In [ ]:
#t=2.3min
tic()
resultado3lineal=learnLinearGraph([1/7,1/7,1/7,1/7,1/7,1/7,1/7],0.5,grafo250obs7,250)
toc()

<h5>n=500<h5>

<h2>Evaluación de recuperación l2 de grafos<h2>

<h5>n=250<h5>

In [9]:
#28 s
tic()
resultado1l2=learnl2Graph([1],0.5,grafo250obs1,250)
toc()

MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (2) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (5) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (7) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (10) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (17) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (18) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (19) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (20) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (21) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (22) of matrix 'A'.
Warning number 710 is disabled.
Problem
  N

75.485795534

In [ ]:
#61 s
tic()
resultado2l2=learnl2Graph([1/3,1/3,1/3],0.5,grafo250obs3,250)
toc()

In [ ]:
#t=2.25 min
tic()
resultado3l2=learnl2Graph([1/7,1/7,1/7,1/7,1/7,1/7,1/7],0.5,grafo250obs7,250)
toc()

<h5>n=500<h5>

In [ ]:
#661 s
tic()
resultado1l2n500=learnl2Graph([1],0.5,grafo500obs1,500)
toc()

In [ ]:
# 2 500 000 constraints
# 876254 variables
# 23.2 min
tic()
resultado2l2n500=learnl2Graph([1/3,1/3,1/3],0.5,grafo500obs3,500)
toc()

In [ ]:
#t=62 min
tic()
resultado3l2n500=learnl2Graph([1/7,1/7,1/7,1/7,1/7,1/7,1/7],0.5,grafo500obs7,500)
toc()

<h2>Evaluación de recuperación espectral de grafos<h2>

In [ ]:
#aparentemente se come mucha memoria en SDP cuando hay muchas interacciones con los constraints. Ver los 
#siguientes links:
#https://groups.google.com/forum/#!topic/yalmip/Wa0QXQOX-_k
#https://docs.mosek.com/8.1/capi/solving-linear.html
#https://github.com/JuliaOpt/JuMP.jl/issues/474
#http://jump.readthedocs.io/en/latest/nlp.html
tic()
resultado1Espectral=learnEspectralGraph([1],0.5,grafo250obs1,250)
toc()

In [ ]:
tic()
resultado2Espectral=learnEspectralGraph([1/3,1/3,1/3],0.5,grafo250obs3,250)
toc()

In [ ]:
#t=2.25 min
tic()
resultado3Espectral=learnEspectralGraph([1/7,1/7,1/7,1/7,1/7,1/7,1/7],0.5,grafo250obs7,250)
toc()

<h2>Pruebas de recuperacion l2<h2>

In [21]:

grafo100obs7 = Array{Any}(12)
grafo100obs7[1]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[2]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[3]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[4]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[5]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[6]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[7]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[8]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[9]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[10]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[11]=erdosgraph([0.75,0.75],0.1,[50,50],100)
grafo100obs7[12]=erdosgraph([0.75,0.75],0.1,[50,50],100)

100×100 Array{Float64,2}:
 0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  …  1.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  …  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0     0.0  0.0  0.0  1.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  0.0  0.0  0.0  0.0  1.0  1.0
 1.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0  1.0  1.

In [22]:
#28 s
tic()
resultado1l2=learnl2Graph((1/12)*ones(12),0.005,grafo100obs7,100)
toc()

MOSEK warning 710: #12 (nearly) zero elements are specified in sparse col '' (13) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (14) of matrix 'A'.
MOSEK warning 710: #5 (nearly) zero elements are specified in sparse col '' (15) of matrix 'A'.
MOSEK warning 710: #1 (nearly) zero elements are specified in sparse col '' (16) of matrix 'A'.
MOSEK warning 710: #3 (nearly) zero elements are specified in sparse col '' (17) of matrix 'A'.
MOSEK warning 710: #5 (nearly) zero elements are specified in sparse col '' (18) of matrix 'A'.
MOSEK warning 710: #3 (nearly) zero elements are specified in sparse col '' (19) of matrix 'A'.
MOSEK warning 710: #2 (nearly) zero elements are specified in sparse col '' (21) of matrix 'A'.
MOSEK warning 710: #2 (nearly) zero elements are specified in sparse col '' (22) of matrix 'A'.
MOSEK warning 710: #4 (nearly) zero elements are specified in sparse col '' (23) of matrix 'A'.
Warning number 710 is disabled.
Problem

27.139488332

In [25]:
resultado1l2[1][1:30,1:30]

30×30 Array{Float64,2}:
 5.08395e-9  1.0         1.0         …  1.0         3.66426e-8  1.0       
 1.0         5.08395e-9  1.0            1.0         0.5         1.0       
 1.0         1.0         5.08395e-9     1.0         1.0         1.0       
 1.0         1.0         1.0            1.0         1.0         1.0       
 1.0         1.0         0.5            1.0         1.0         1.0       
 1.0         1.0         1.0         …  1.0         1.0         1.0       
 1.0         1.0         1.0            1.0         1.0         1.0       
 1.0         1.0         1.0            1.0         1.0         1.0       
 1.0         1.0         1.0            1.0         1.0         1.0       
 1.0         1.0         1.0            1.0         1.0         1.0       
 1.0         1.0         1.0         …  1.0         1.0         1.0       
 1.0         1.0         1.0            1.0         1.0         1.0       
 1.0         0.5         1.0            1.0         1.0         1.0       
 

In [24]:
grafo100obs7[1][1:6,1:6]

6×6 Array{Float64,2}:
 0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  0.0  1.0
 0.0  1.0  0.0  0.0  0.0  1.0
 1.0  0.0  1.0  1.0  1.0  0.0

In [19]:
grafo100obs7[7][1:6,1:6]

6×6 Array{Float64,2}:
 0.0  1.0  1.0  1.0  1.0  0.0
 1.0  0.0  1.0  1.0  1.0  1.0
 1.0  1.0  0.0  1.0  1.0  1.0
 1.0  1.0  1.0  0.0  1.0  0.0
 1.0  1.0  1.0  1.0  0.0  0.0
 0.0  1.0  1.0  0.0  0.0  0.0

In [10]:

grafo250obs3 = Array{Any}(10)
grafo250obs3[1]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[2]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[3]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[4]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[5]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[6]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[7]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[8]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[9]=erdosgraph([0.75,0.75],0.2,[25,25],50)
grafo250obs3[10]=erdosgraph([0.75,0.75],0.2,[25,25],50)



50×50 Array{Float64,2}:
 0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  …  0.0  1.0  1.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  1.0  0.0  1.0
 1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0     0.0  1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0     0.0  1.0  0.0  0.0  0.0  0.0  1.0
 0.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  1.0  0.0  0.0
 1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  …  0.0  0.0  1.0  0.0  0.0  0.0  1.0
 1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0 

In [11]:
#28 s
tic()
resultado1l2=learnl2Graph((1/10)*ones(10),0.005,grafo250obs3,50)
toc()

MOSEK warning 710: #10 (nearly) zero elements are specified in sparse col '' (11) of matrix 'A'.
MOSEK warning 710: #3 (nearly) zero elements are specified in sparse col '' (12) of matrix 'A'.
MOSEK warning 710: #2 (nearly) zero elements are specified in sparse col '' (13) of matrix 'A'.
MOSEK warning 710: #3 (nearly) zero elements are specified in sparse col '' (14) of matrix 'A'.
MOSEK warning 710: #2 (nearly) zero elements are specified in sparse col '' (15) of matrix 'A'.
MOSEK warning 710: #6 (nearly) zero elements are specified in sparse col '' (16) of matrix 'A'.
MOSEK warning 710: #4 (nearly) zero elements are specified in sparse col '' (17) of matrix 'A'.
MOSEK warning 710: #3 (nearly) zero elements are specified in sparse col '' (18) of matrix 'A'.
MOSEK warning 710: #2 (nearly) zero elements are specified in sparse col '' (19) of matrix 'A'.
MOSEK warning 710: #3 (nearly) zero elements are specified in sparse col '' (20) of matrix 'A'.
Warning number 710 is disabled.
Problem

4.654798855

In [15]:
round.(resultado1l2[1][20:30,20:30],2)

11×11 Array{Float64,2}:
 0.0  0.5  1.0  1.0  1.0  1.0  0.5  0.0  0.0  0.0  0.0
 0.5  0.0  0.5  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.5  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.5  0.0  0.0
 1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.5  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.5
 0.0  0.0  0.0  0.5  0.0  0.0  1.0  1.0  0.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.5  1.0  1.0  0.0