In [ ]:
s = @spawnat 2 1

In [ ]:
#vamos a intentar paralelizar la funcion
@everywhere function sumar(A)
    a = sum(A)
    return(a)
end

In [ ]:
sumar(mat1)

In [ ]:
mat1

In [ ]:
nprocs()

In [ ]:
addprocs(1)

In [ ]:
mat1 = rand(5,5)

In [ ]:
bli = @spawn sumar(mat1)

In [ ]:
fetch(bli)

In [ ]:
 mat1[shuffle(1:end), :]

In [ ]:
using NBInclude
nbinclude("AuxFunctions.ipynb")
#nbinclude("GraphLearning.ipynb")

In [ ]:
 mat1[shuffle(1:end), :]

In [ ]:
grafo10obs3 = Array{Any}(3)
grafo10obs3[1]=erdosgraph([0.9,0.9],0.1,[3,7],10)+diagm(ones(10))
grafo10obs3[2]=erdosgraph([0.9,0.9],0.1,[3,7],10)+diagm(ones(10))
grafo10obs3[3]=erdosgraph([0.9,0.9],0.1,[3,7],10)+diagm(ones(10))
1

In [ ]:
revuelve=shuffle(1:10)

In [ ]:
grafo10obs3[1]=grafo10obs3[1][revuelve,revuelve]
grafo10obs3[2]=grafo10obs3[2][revuelve,revuelve]
grafo10obs3[3]=grafo10obs3[3][revuelve,revuelve]
1

In [ ]:
recuperaRegular = learnRegularized2A([1/3,1/3,1/3],1.6,grafo10obs3,10)


In [ ]:
recuperaRegular[1]

In [ ]:
recup = round.(recuperaRegular[1])

In [ ]:
Pkg.add("LightGraphs")

In [ ]:
using LightGraphs

In [ ]:
 g = PathGraph(6)

In [ ]:
A = [1 1 0; 1 1 0; 0 0 1]

In [ ]:
g = Graph(A)

In [ ]:
connected_components(g)

In [ ]:
mat1=erdosgraph([1,1],0,[3,7],10)+diagm(ones(10))


In [ ]:
asdf=shuffle(1:10)

In [ ]:
mat1 =mat1[asdf,asdf]

In [ ]:
g = Graph(mat1)

In [ ]:
connected_components(g)

In [ ]:
function SoftThreshold(W,perturbation)
    map(W) do x
        perturb(x,perturbation)
    end
end



#Method for perturbing x given epsilon. Used in the softThresholding function.
function perturb(x,epsilon)
    if x>epsilon 
        return x-epsilon
    end
    if x<-epsilon
        return x+epsilon
    else
        return(0)
    end
end


In [ ]:
function solveForXprox(obs,Y,Z,mu,n)
#    actualizado = SoftThreshold(Z-(1/mu)*Y-obs,1/mu)+obs
    actualizado = SoftThreshold(Z-(1/mu)*Y-obs,1/(2*mu))+obs
    return(actualizado)
end    


In [ ]:
grafo10obs3 = Array{Any}(3)
grafo10obs3[1]=erdosgraph([0.9,0.9],0.1,[3,7],10)+diagm(ones(10))
grafo10obs3[2]=erdosgraph([0.9,0.9],0.1,[3,7],10)+diagm(ones(10))
grafo10obs3[3]=erdosgraph([0.9,0.9],0.1,[3,7],10)+diagm(ones(10))

In [ ]:
mat3=erdosgraph([0.9,0.9],0.1,[250,750],1000)+diagm(ones(1000))

In [ ]:
tic()
SoftThreshold(mat3,0.3125)
toc()

In [ ]:
1/3.2

In [ ]:
tic()
perturb.(mat1,0.3125)
toc()

In [1]:
using NBInclude
#using LightGraphs
nbinclude("C:\\Users\\Daniel\\MasterThesis\\admmRecovery.ipynb")

In [ ]:
euObs = Array{Any}(1)
euObs[1]= erdosgraph([0.65,0.65,0.65,0.65],0.2,[250,250,250,250],1000)+diagm(ones(1000))

In [ ]:
recover=admmRecovery(euObs,2.3,1000,1.6,1.0e-4,300)


In [2]:
256.7/60

4.278333333333333

In [1]:
mat1 = randn(1000,1000)
tic()
svd(mat1)
toc()

elapsed time: 1.015080618 seconds


1.015080618

In [3]:
mat1 = [1 1 3; 3 5 1; 2 6 4]

3×3 Array{Int64,2}:
 1  1  3
 3  5  1
 2  6  4

In [5]:
fact1 = svdfact(mat1)

Base.LinAlg.SVD{Float64,Float64,Array{Float64,2}}([-0.265414 -0.712482 0.649557; -0.580553 0.655991 0.482321; -0.769749 -0.249088 -0.587743], [9.647, 2.80433, 1.03499], [-0.367635 -0.80716 -0.461884; 0.270053 0.382604 -0.883564; 0.889897 -0.449562 0.0773172])

In [7]:
fact1[:U]

3×3 Array{Float64,2}:
 -0.265414  -0.712482   0.649557
 -0.580553   0.655991   0.482321
 -0.769749  -0.249088  -0.587743

In [8]:
fact1[:S]

3-element Array{Float64,1}:
 9.647  
 2.80433
 1.03499

In [9]:
fact1[:Vt]

3×3 Array{Float64,2}:
 -0.367635  -0.80716   -0.461884 
  0.270053   0.382604  -0.883564 
  0.889897  -0.449562   0.0773172

In [10]:
fact2 =svd(mat1)

([-0.265414 -0.712482 0.649557; -0.580553 0.655991 0.482321; -0.769749 -0.249088 -0.587743], [9.647, 2.80433, 1.03499], [-0.367635 0.270053 0.889897; -0.80716 0.382604 -0.449562; -0.461884 -0.883564 0.0773172])

In [11]:
fact2[1]

3×3 Array{Float64,2}:
 -0.265414  -0.712482   0.649557
 -0.580553   0.655991   0.482321
 -0.769749  -0.249088  -0.587743

In [12]:
fact2[2]

3-element Array{Float64,1}:
 9.647  
 2.80433
 1.03499

In [13]:
fact2[3]

3×3 Array{Float64,2}:
 -0.367635   0.270053   0.889897 
 -0.80716    0.382604  -0.449562 
 -0.461884  -0.883564   0.0773172

In [ ]:
cd("C:/Users/Daniel/MasterThesis/GraphProyects/NipCollabs")
include("pruebaADMM.jl")
Nips = Array{Any}(6)
Nips[1]= readdlm("nips21.txt")+diagm(ones(5722))
Nips[2]= readdlm("nips22.txt")+diagm(ones(5722))
Nips[3]= readdlm("nips23.txt")+diagm(ones(5722))
Nips[4]= readdlm("nips24.txt")+diagm(ones(5722))
Nips[5]= readdlm("nips25.txt")+diagm(ones(5722))
Nips[6]= readdlm("nips26.txt")+diagm(ones(5722))

tic()
recover=admmRecovery(Nips,3,5722,1.6,1.0e-4,200)
toc()
RealRecovery=(recover[1]+ones(5722)*ones(5722)')/2
writedlm("NipsRecovered.txt",RealRecovery)

In [19]:
tic()
singValDesc = svdfact(mat1)
toc()

elapsed time: 0.95767606 seconds


0.95767606

In [21]:
tic()
Z = singValDesc[:U]*(diagm(singValDesc[:S])*singValDesc[:Vt])
toc()
Z

elapsed time: 0.195563683 seconds


1000×1000 Array{Float64,2}:
 -0.524587   -1.36845     0.0962655  …  -0.568819   -2.36363    1.01624  
 -0.647133   -0.718962    1.2681        -0.464929   -0.925547   1.29815  
 -0.726949   -1.66703     1.36015       -1.26581    -0.874583  -0.0743908
 -0.252659    1.15193     1.07875       -0.591441    0.234644  -0.166097 
 -0.377012    1.12742    -0.574232      -1.11853    -0.171567  -0.438598 
  1.04553     1.17693    -0.453178   …   0.779399   -0.909639   1.39379  
 -0.392305    2.22719    -0.384819       1.70521    -0.383975  -0.870332 
  2.55664    -0.490191   -1.37538       -1.17022    -1.19008   -1.62265  
 -0.732283   -0.746533    1.28218       -1.045      -0.232921   0.167483 
  0.749854   -0.405137   -1.03894        0.0828048   0.110496   0.388229 
  0.394458   -0.963022    0.492247   …  -0.543118    0.952909  -1.97382  
 -1.47758     0.144909   -0.466203       0.151511   -0.496114   0.0230741
  0.0425463  -0.595528    0.745858      -1.92775    -0.798215   0.103108 
  ⋮       

In [25]:
tic()
p=*(singValDesc[:U],diagm(singValDesc[:S]),singValDesc[:Vt])
toc()

elapsed time: 0.143253236 seconds


0.143253236

In [26]:
p

1000×1000 Array{Float64,2}:
 -0.524587   -1.36845     0.0962655  …  -0.568819   -2.36363    1.01624  
 -0.647133   -0.718962    1.2681        -0.464929   -0.925547   1.29815  
 -0.726949   -1.66703     1.36015       -1.26581    -0.874583  -0.0743908
 -0.252659    1.15193     1.07875       -0.591441    0.234644  -0.166097 
 -0.377012    1.12742    -0.574232      -1.11853    -0.171567  -0.438598 
  1.04553     1.17693    -0.453178   …   0.779399   -0.909639   1.39379  
 -0.392305    2.22719    -0.384819       1.70521    -0.383975  -0.870332 
  2.55664    -0.490191   -1.37538       -1.17022    -1.19008   -1.62265  
 -0.732283   -0.746533    1.28218       -1.045      -0.232921   0.167483 
  0.749854   -0.405137   -1.03894        0.0828048   0.110496   0.388229 
  0.394458   -0.963022    0.492247   …  -0.543118    0.952909  -1.97382  
 -1.47758     0.144909   -0.466203       0.151511   -0.496114   0.0230741
  0.0425463  -0.595528    0.745858      -1.92775    -0.798215   0.103108 
  ⋮       

In [24]:
using NBInclude
#using LightGraphs
nbinclude("C:\\Users\\Daniel\\MasterThesis\\admmRecovery.ipynb")
using LightGraphs
nbinclude("AuxFunctions.ipynb")

evaluarADMMGraphLearning4 (generic function with 2 methods)

In [17]:
a =7
b =2

2

In [18]:
abs(sqrt(a)-sqrt(b))

1.2315377486914956

In [12]:
n=100

100

In [23]:
intra = a*log(n)/n

0.3223619130191664

In [22]:
outra = b*log(n)/n

0.09210340371976183

In [ ]:
log()

In [27]:

euObs = Array{Any}(3)
euObs[1]= erdosgraph([intra,intra],outra,[60,40],100)+diagm(ones(100))
euObs[2]= erdosgraph([intra,intra],outra,[60,40],100)+diagm(ones(100))
euObs[3]= erdosgraph([intra,intra],outra,[60,40],100)+diagm(ones(100))

100×100 Array{Float64,2}:
 1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  …  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  0.0  1.0  1.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.

In [28]:
recover=admmRecovery(euObs,1.5,100,1.6,1.0e-4,300)


solving for x...
Solved, now solving for Z
elapsed time: 4.056314661 seconds
solved. now solving Y
Step 0
0.8
solving for x...
Solved, now solving for Z
elapsed time: 0.007012934 seconds
solved. now solving Y
Step 1
0.8
solving for x...
Solved, now solving for Z
elapsed time: 0.007140435 seconds
solved. now solving Y
Step 2
0.8
solving for x...
Solved, now solving for Z
elapsed time: 0.008415837 seconds
solved. now solving Y
Step 3
0.8
solving for x...
Solved, now solving for Z
elapsed time: 0.007499648 seconds
solved. now solving Y
Step 4
0.8
solving for x...
Solved, now solving for Z
elapsed time: 0.007552543 seconds
solved. now solving Y
Step 5
0.8
solving for x...
Solved, now solving for Z
elapsed time: 0.00705675 seconds
solved. now solving Y
Step 6
0.8
solving for x...
Solved, now solving for Z
elapsed time: 0.011122958 seconds
solved. now solving Y
Step 7
0.8
solving for x...
Solved, now solving for Z
elapsed time: 0.007360305 seconds
solved. now solving Y
Step 8
0.8
solving for

([-0.638712 -0.999999 … -0.999983 -0.999989; -0.999999 0.173802 … -0.999965 -1.00002; … ; -0.999983 -0.999965 … 0.999999 0.140492; -0.999989 -1.00002 … 0.140492 -0.317471], Any[[-0.638712 -1.0 … -1.0 -1.0; -1.0 0.173802 … -1.0 -1.0; … ; -1.0 -1.0 … 1.0 0.140492; -1.0 -1.0 … 0.140492 -0.317471], [-0.638712 -1.0 … -1.0 -1.0; -1.0 0.173802 … -1.0 -1.0; … ; -1.0 -1.0 … 1.0 0.140492; -1.0 -1.0 … 0.140492 -0.317471], [-0.638712 -1.0 … -1.0 -1.0; -1.0 0.173802 … -1.0 -1.0; … ; -1.0 -1.0 … 1.0 0.140492; -1.0 -1.0 … 0.140492 -0.317471]])

In [29]:
RealRecovery=(recover[1]+ones(100)*ones(100)')/2


100×100 Array{Float64,2}:
  0.180644     5.83402e-7   1.16516e-7  …   8.53434e-6    5.66343e-6 
  5.83402e-7   0.586901     0.057008        1.73999e-5   -8.64227e-6 
  1.16516e-7   0.057008     0.913056       -2.4354e-5    -4.32095e-6 
  7.81677e-7   7.61911e-7   0.348546        2.11886e-5   -7.48161e-6 
  0.0610563    0.20411      0.0996673      -3.77751e-5    4.33889e-5 
  2.87794e-6   5.60052e-6   0.0695008   …   5.32272e-5   -2.185e-5   
  0.163653     1.60554e-7  -2.27687e-6     -1.09311e-5   -3.5611e-5  
  9.26311e-7   1.26418e-6   5.24666e-7      1.30916e-5   -2.02724e-5 
  0.104147     2.90682e-7   0.462334        1.59247e-6    2.93732e-5 
  8.91703e-7  -2.08334e-6   0.0682998       2.57475e-5    1.93722e-5 
 -4.40142e-7   8.17305e-8   1.0         …   1.55619e-5    3.69235e-6 
 -1.13147e-7  -1.14538e-7  -6.29933e-7      7.55598e-6   -3.45327e-5 
  2.31556e-6   0.330957     0.196675        1.87689e-7   -1.98407e-5 
  ⋮                                     ⋱                       

In [ ]:
g = Graph(RealRecovery)
comps =connected_components(g)