In [ ]:
#This notebook contains a quick implementation of the robust pca algorithm.
#We solve the problem using the implementation of "The Augmented Lagrange Multiplier
#method for exact recovery of corrupted low-rank matrices"
#In the end, we also use a solver to compare times and overall performance.
#We expect to find much more promising results using the implemantation on the latter paper:
#"/although interior point methods normally take very few iterations t converge, they have difficulty in
#handling large matrices because of the complexity of computing the step direction is O(m^6), where m is the dimension of 
#matrix [...] generic interior point solvers are too limited for Robust PCA ".

#Note that the robust PCA is used in many context. Ours is the clique problem which deals with nxn symetric matrices
#. However this implementation works for m x n matrices.



In [ ]:
# The model
#D- a m x n matrix of data/variables. Usually D is nxn graph adjacency matrix.
# We seek to solve the problem min a||E||_1 + ||A||_* subject to E+A = D+I 
#a is a positive real number. 


In [ ]:
#rpca is the main function. 
#If D is square matrix, we redefine D to be D = D+I.

function rpca(D,lambda,stopCrit1=1.0e-7,stopCrit2=1.0e-5,maxIter=1000)
    #Initialization
    dims =size(D)
    if dims[1]==dims[2]
        D = D+I
    end    
    mu = 1.25/norm(D)
    ro=1.6    
    E = zeros(D)
    k = 0
    Y = D/J(D)
        #Iteraciones
    while ~firstCriterium(stopCrit1,D,A_k,E_k) || ~secondCriterium(stopCrit2,E_k,E_k1)    
        # First solve A_k+1 = arg min L(A,E_k,Y_k,mu_k)
        singValDesc = svd(D-E+((1/mu)*Y))
        #SVD(A) returns a triple (U,S,V) where S contains the singular values and A=U*S*V' (' denotes ')
        #for SVD(A) to work correctly, A must be m x n where m>= n or else S wont have the proper dimensions.
        A = U*perturb(S,1/mu)*V'
        #Now solve E_k+1= arg min L(A_k+1,E,Y_k,mu_k)
        perturbFactor = lambda*(1/mu)
        E = perturb(D-A+((1/mu)*Y),perturbFactor)
        Y = Y + mu*(D-A-E)
        updateMu(mu)
        k=k+1
        println("voy en el paso $(k)")        
    end
    return(A,E)
end


In [ ]:
#Stoping criteria functions  

function firstCriterium(stopCrit1,D,A_k,E_k)
    asdf
end 

function secondCriterium(stopCrit2,E_k,E_k1)
    asdf
end


    


In [ ]:
# Updating functions

function updateMu(mu,rho,Ek,Ek_1,D,epsilon2)
    asdf
end






In [50]:
#Other useful operators

#perturbation operator
#X is a m x n matriz to perturb
#epsilon is the perturbation
function perturb(A,perturbation)
    map(A) do x
        f(x,perturbation)
    end
end


#J operator
#D is an m x n matriz
#lambda : parameter of the robust pca
function J(D,lambda)
    return max(norm(A,2),(1/lambda)*maximum(abs(A)))
end

function f(x,epsilon)
    if x>epsilon 
        return x-epsilon
    end
    if x<-epsilon
        return x+epsilon
    else
        return(0)
    end
end




J (generic function with 2 methods)

In [57]:
A = [3 2 2 ; 2 3 -2]

2×3 Array{Int64,2}:
 3  2   2
 2  3  -2

In [58]:
fact = svdfact(A)

Base.LinAlg.SVD{Float64,Float64,Array{Float64,2}}([-0.707107 -0.707107; -0.707107 0.707107],[5.0,3.0],[-0.707107 -0.707107 -5.55112e-17; -0.235702 0.235702 -0.942809])

In [59]:
fact[:S]

2-element Array{Float64,1}:
 5.0
 3.0

In [63]:
diagm(fact[:S],1)

3×3 Array{Float64,2}:
 0.0  5.0  0.0
 0.0  0.0  3.0
 0.0  0.0  0.0

In [72]:
println("voy en el paso $(3)")

voy en el paso 3


In [69]:
"1 + 2 = $(1 + 2)"

"1 + 2 = 3"