In [2]:
#call the necesary notebooks and packages...
using NBInclude
using LightGraphs
@nbinclude("C:\\Users\\Daniel\\MasterThesis\\admmRecovery.ipynb")

<h2>First, set the period 2012-2013, set senators, then subject = economia<h2>

In [3]:
#Read matrices...
Eco1 = readdlm("Economia1.txt")
Eco2 = readdlm("Economia2.txt")
Eco3 = readdlm("Economia3.txt")
Eco4 = readdlm("Economia4.txt")

#store them in an array
EcoSenadores = Array{Any}(4)
EcoSenadores[1]= Eco1
EcoSenadores[2]= Eco2
EcoSenadores[3]= Eco3
EcoSenadores[4]= Eco4



156×156 Array{Float64,2}:
 1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0     0.0  1.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0     0.0  1.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0     0.0  1.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0     0.0  1.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.

In [ ]:
issymmetric(Eco4)

In [ ]:
function recover(obs,lambda,n,rho,err,iter)
    recv = admmRecovery(obs,lambda,n,rho,err,iter)
    RealRecov=(recv[1]+ones(n)*ones(n)')/2
    recvRounded = round.(RealRecov)
    #checks symmetry
    if(issymmetric(recvRounded[1:n,1:n])==false)
        return("ERROR, non symetric matrix recovered.")
    end
    g = Graph(recvRounded)
    conected = connected_components(g)
    maximal_cliques(g)

In [56]:
##### recover the clusters...
recover=admmRecovery(EcoSenadores,0.001,156,3,1.0e-3,1000)


elapsed time: 0.015639575 seconds
1.5
elapsed time: 0.015442994 seconds
0.75
elapsed time: 0.015582337 seconds
0.375
elapsed time: 0.015597338 seconds
0.1875
elapsed time: 0.015450099 seconds
0.09375
elapsed time: 0.016090762 seconds
0.046875
elapsed time: 0.016065103 seconds
0.046875
elapsed time: 0.015842471 seconds
0.046875
elapsed time: 0.017282085 seconds
0.046875
elapsed time: 0.018672358 seconds
0.046875
elapsed time: 0.019980523 seconds
0.046875
elapsed time: 0.016983268 seconds
0.046875
elapsed time: 0.016826951 seconds
0.046875
elapsed time: 0.016014577 seconds
0.046875
elapsed time: 0.01609313 seconds
0.046875
elapsed time: 0.016311026 seconds
0.046875
elapsed time: 0.016347736 seconds
0.046875
elapsed time: 0.015940366 seconds
0.046875
elapsed time: 0.016024445 seconds
0.046875
elapsed time: 0.016188263 seconds
0.046875
elapsed time: 0.016807608 seconds
0.046875
elapsed time: 0.01724419 seconds
0.046875
elapsed time: 0.016627608 seconds
0.046875
elapsed time: 0.015883918 se

LoadError: Base.LinAlg.LAPACKException(1)

0.0234375


In [57]:
#real matrix
RealRecovery=(recover[1]+ones(156)*ones(156)')/2


156×156 Array{Float64,2}:
  1.0           0.5           0.997605     …   0.00239491    4.996e-16  
  0.5           1.0           0.997605         5.05151e-15   5.38458e-15
  0.997605      0.997605      1.0             -1.33227e-15  -4.44089e-16
  0.5           0.00239491    0.00239491       0.00239491    8.60423e-15
  0.5           0.00239491    0.00239491       0.00239491    0.00239491 
  2.77556e-16  -9.65894e-15  -3.33067e-16  …  -1.77636e-15   6.10623e-15
  0.5           0.00239491    0.00239491       0.00239491    0.00239491 
 -3.33067e-16  -5.66214e-15   3.21965e-15     -3.33067e-16  -5.55112e-15
  0.5           0.997605      0.997605        -2.22045e-16  -1.11022e-16
  0.00239491    0.5           0.5             -7.77156e-16   0.00239491 
  0.00239491    0.5           0.5          …  -3.21965e-15  -4.44089e-16
  0.997605      0.5           0.5              0.00239491    0.00239491 
  0.5           0.997605      0.997605        -2.77556e-15   0.00239491 
  ⋮                      

In [58]:
recuperaRedondeada = round.(RealRecovery)

156×156 Array{Float64,2}:
  1.0   0.0   1.0   0.0   0.0  -0.0  …   0.0   0.0   0.0  -0.0   0.0   0.0
  0.0   1.0   1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  1.0   1.0   1.0   0.0   0.0   0.0     -0.0   0.0   0.0   0.0  -0.0  -0.0
  0.0   0.0   0.0   1.0   1.0   0.0      0.0  -0.0  -0.0  -0.0   0.0   0.0
  1.0   0.0   0.0   1.0   1.0   0.0      0.0  -0.0   0.0   0.0   0.0   0.0
  0.0  -0.0  -0.0   0.0   0.0   1.0  …   0.0  -0.0  -0.0  -0.0  -0.0   0.0
  0.0   0.0   0.0   0.0   1.0   0.0      0.0   0.0   0.0  -0.0   0.0   0.0
 -0.0  -0.0   0.0  -0.0  -0.0   1.0     -0.0  -0.0   0.0  -0.0  -0.0  -0.0
  0.0   1.0   1.0   0.0   0.0  -0.0      0.0   0.0  -0.0   0.0  -0.0  -0.0
  0.0   0.0   1.0   0.0   1.0   0.0      0.0  -0.0   0.0   0.0  -0.0   0.0
  0.0   0.0   1.0   0.0   0.0   0.0  …   0.0   0.0  -0.0   0.0  -0.0  -0.0
  1.0   0.0   0.0   0.0   1.0   0.0      0.0   0.0   0.0  -0.0   0.0   0.0
  0.0   1.0   1.0   0.0   0.0   0.0      0.0  -0.0   0.0   0.0  -0.0   0.0

In [59]:
issymmetric(recuperaRedondeada[1:156,1:156])

false

In [15]:
#save results
writedlm("EcoRecovered.txt",recuperaRedondeada,",")

In [51]:
#Conected components
gEco = Graph(recuperaRedondeada)
conected = connected_components(gEco)

LoadError: ArgumentError: Adjacency / distance matrices must be symmetric

In [ ]:
conexiones = function(f)
    return(
    

In [16]:
plo=map(length,conected)

130-element Array{Int64,1}:
  1
  1
 27
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
  ⋮
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1

In [25]:
sort(plo)

130-element Array{Int64,1}:
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
  ⋮
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
  1
 27

<h2>Set the period 2012-2013,set senators, All subjects<h2>

In [ ]:
#read matrices and save them in an array
proyects =  Array{Any}(26)
#"4Economia"
proyects[1]= readdlm("proyectoEconomia1.txt")
proyects[2]= readdlm("proyectoEconomia2.txt")
proyects[3]=  readdlm("proyectoEconomia3.txt")
proyects[4]=  readdlm("proyectoEconomia4.txt")
# "1Corrupcion"
proyects[5]=  readdlm("proyectoCorrupcion1.txt")
# "1Tr nsito y transporte"
proyects[6]=  readdlm("proyectotransporte1.txt")
# "2Seguridad, defensa y fuerza publica"
proyects[7]=  readdlm("proyectoSeguridad, defensa y fuerza publica1.txt")
proyects[8]= readdlm("proyectoSeguridad, defensa y fuerza publica2.txt")
# "1Rama Ejecutiva"
proyects[9]= readdlm("proyectoRama Ejecutiva1.txt")
# "2Seguridad Social y salud"
proyects[10]=  readdlm("proyectoSeguridad Social y salud1.txt")
proyects[11]= readdlm("proyectoSeguridad Social y salud2.txt")
#"4Politica Internacional"
proyects[12]=  readdlm("proyectoPolitica Internacional1.txt")
proyects[13]=  readdlm("proyectoPolitica Internacional2.txt")
proyects[14]=  readdlm("proyectoPolitica Internacional3.txt")
proyects[15]=  readdlm("proyectoPolitica Internacional4.txt")
# "2Estampillas"
proyects[16]=  readdlm("proyectoEstampillas1.txt")
proyects[17]=  readdlm("proyectoEstampillas2.txt")
# "3Celebraciones, honores y monumentos"
proyects[18]=  readdlm("proyectoCelebraciones, honores y monumentos1.txt")
proyects[19]=  readdlm("proyectoCelebraciones, honores y monumentos2.txt")
proyects[20]=  readdlm("proyectoCelebraciones, honores y monumentos3.txt")
# "1Comercio, industria y turismo"
proyects[21]=  readdlm("proyectoComercio, industria y turismo1.txt")
# "1Impuestos"
proyects[22]=  readdlm("proyectoImpuestos1.txt")
# "2Presupuesto"
proyects[23]= readdlm("proyectoPresupuesto1.txt")
proyects[24]= readdlm("proyectoPresupuesto2.txt")
# "1Minas y energia"
proyects[25]=  readdlm("proyectoMinas y energia1.txt")
# "1Conflicto armado"
 proyects[26]= readdlm("proyectoConflicto armado1.txt")




In [ ]:
recoverProyects=admmRecovery(proyects,7,156,3,1.0e-4,1000)


In [ ]:
#real matrix
RealProyects=(recoverProyects[1]+ones(156)*ones(156)')/2


In [ ]:
RoundedRecover = round.(RealProyects)

In [ ]:
issymmetric(RoundedRecover)
#issymmetric(recuperaRedondeada[1:156,1:156])

In [ ]:
#Conected components
gProyects = Graph(RoundedRecover)
compo =connected_components(gProyects)

In [ ]:
compo[1]

In [1]:
1000/1.2

833.3333333333334

In [2]:
833/60

13.883333333333333