In [2]:
#call the necesary notebooks and packages...
using NBInclude
using LightGraphs
@nbinclude("C:\\Users\\Daniel\\MasterThesis\\admmRecovery.ipynb")

In [3]:
#Read the matrix
euGraph = readdlm("euCore.txt")
euObs = Array{Any}(1)
euObs[1]= euGraph

1005×1005 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  …  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0  0.0  

In [4]:
issymmetric(euGraph)

true

In [18]:
#recover the clusters...
recover=admmRecovery(euObs,14,1005,3.2,1.0e-3,2000)


elapsed time: 1.289261699 seconds
3.2
elapsed time: 1.269216422 seconds
1.6
elapsed time: 1.260748466 seconds
1.6
elapsed time: 1.305275499 seconds
1.6
elapsed time: 1.329594227 seconds
1.6
elapsed time: 1.359821025 seconds
1.6
elapsed time: 1.280810716 seconds
1.6
elapsed time: 1.303784962 seconds
1.6
elapsed time: 1.582863166 seconds
1.6
elapsed time: 1.7941318 seconds
1.6
elapsed time: 2.031129567 seconds
1.6
elapsed time: 1.657817129 seconds
1.6
elapsed time: 1.705997872 seconds
1.6
elapsed time: 1.408623484 seconds
1.6
elapsed time: 1.388937025 seconds
1.6
elapsed time: 1.625578343 seconds
1.6
elapsed time: 1.750794512 seconds
1.6
elapsed time: 1.689827755 seconds
0.8
elapsed time: 2.085437855 seconds
0.8
elapsed time: 1.423093457 seconds
0.8
elapsed time: 1.405902938 seconds
0.8
elapsed time: 1.273261715 seconds
0.8
elapsed time: 1.363358288 seconds
0.8
elapsed time: 1.301589419 seconds
0.8
elapsed time: 1.483204418 seconds
0.8
elapsed time: 1.424555572 seconds
0.8
elapsed time: 

([-1.0 -1.0 … -1.0 -1.0; -1.0 -0.330453 … -1.0 -1.0; … ; -1.0 -1.0 … -1.0 -1.0; -1.0 -1.0 … -1.0 -1.0], Any[[-1.0 -1.0 … -1.0 -1.0; -1.0 -0.330453 … -1.0 -1.0; … ; -1.0 -1.0 … -1.0 -1.0; -1.0 -1.0 … -1.0 -1.0]])

1.6
exceeded max number of iteration at solving


In [26]:
#real matrix
RealRecovery=(recover[1]+ones(1005)*ones(1005)')/2


1005×1005 Array{Float64,2}:
 -1.92071e-8    1.09314e-7  -2.44421e-8  …  -7.76512e-9   -4.50464e-10
  1.09314e-7    0.334774     0.215874        1.10345e-8    3.94581e-9 
 -2.44421e-8    0.215874     0.139202       -1.22598e-8    5.86093e-9 
 -2.88322e-8    0.348297     0.224593        2.28883e-8    1.59209e-8 
 -5.30782e-8    0.13565      0.0874715      -3.30582e-8   -1.27985e-8 
  2.07626e-8    0.258696     0.166816    …  -1.58894e-8   -6.2583e-9  
 -1.74949e-8    5.2464e-8   -1.0869e-8      -6.46696e-9   -2.143e-9   
 -2.54028e-8    1.25986e-7  -8.64206e-8     -1.15691e-8   -1.02449e-10
  8.91203e-9   -4.60017e-8   2.04489e-8     -1.47602e-9   -1.23851e-9 
  4.40777e-8   -1.90233e-7   1.2999e-7       7.27177e-9   -2.67045e-9 
  4.1599e-9    -1.72009e-9   1.33158e-8  …  -4.40251e-10   1.56423e-9 
  4.71902e-8   -1.27125e-7   8.87156e-8      8.18638e-9    3.39332e-9 
 -1.53151e-8    0.0302177    0.0194857      -2.53452e-8    5.05689e-9 
  ⋮                                      ⋱       

In [27]:
norm(euGraph-RealRecovery,2)

59.25158533855482

In [28]:
norm(RealRecovery,2)

40.5761950802317

In [29]:
realRounded=round.(RealRecovery)


1005×1005 Array{Float64,2}:
 -0.0   0.0  -0.0  -0.0  -0.0   0.0  …  -0.0  -0.0   0.0  -0.0  -0.0  -0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0  -0.0   0.0   0.0   0.0
 -0.0   0.0   0.0   0.0   0.0   0.0     -0.0  -0.0   0.0  -0.0  -0.0   0.0
 -0.0   0.0   0.0   0.0   0.0   0.0     -0.0   0.0   0.0   0.0   0.0   0.0
 -0.0   0.0   0.0   0.0   0.0   0.0     -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
  0.0   0.0   0.0   0.0   0.0   0.0  …   0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0   0.0  -0.0   0.0  -0.0  -0.0     -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0   0.0  -0.0  -0.0  -0.0   0.0     -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
  0.0  -0.0   0.0   0.0   0.0  -0.0      0.0   0.0  -0.0   0.0  -0.0  -0.0
  0.0  -0.0   0.0   0.0   0.0  -0.0      0.0   0.0  -0.0   0.0   0.0  -0.0
  0.0  -0.0   0.0   0.0  -0.0  -0.0  …   0.0   0.0   0.0   0.0  -0.0   0.0
  0.0  -0.0   0.0   0.0   0.0   0.0      0.0   0.0  -0.0   0.0   0.0   0.0
 -0.0   0.0   0.0   0.0   0.0   0.0     -0.0  -0.0   0.0  -0.0  -0.0   0

In [30]:
norm(euGraph-realRounded,2)

63.269743630491604

In [23]:
#save results
writedlm("EuRecovered.txt",RealRecovery)


In [23]:
issymmetric(realRounded)

true

In [31]:
#Conected components
g = Graph(realRounded)
connected_components(g)
#weakly_connected_components(g)
#strongly_connected_components(g)

953-element Array{Array{Int64,1},1}:
 [1]   
 [2]   
 [3]   
 [4]   
 [5]   
 [6]   
 [7]   
 [8]   
 [9]   
 [10]  
 [11]  
 [12]  
 [13]  
 ⋮     
 [994] 
 [995] 
 [996] 
 [997] 
 [998] 
 [999] 
 [1000]
 [1001]
 [1002]
 [1003]
 [1004]
 [1005]

In [25]:
 maximal_cliques(g)

971-element Array{Array{Int64,1},1}:
 [306]
 [29] 
 [74] 
 [905]
 [176]
 [892]
 [285]
 [318]
 [873]
 [975]
 [354]
 [610]
 [563]
 ⋮    
 [928]
 [812]
 [632]
 [618]
 [341]
 [186]
 [321]
 [420]
 [6]  
 [856]
 [322]
 [218]

In [32]:
p= Graph(euGraph)
maximal_cliques(p)

42690-element Array{Array{Int64,1},1}:
 [74, 513, 166, 173, 121, 87, 21]                    
 [74, 513, 166, 173, 121, 340]                       
 [74, 513, 166, 222, 121, 226]                       
 [74, 513, 166, 222, 121, 87, 21]                    
 [74, 513, 166, 222, 459, 226, 218]                  
 [74, 513, 166, 222, 459, 87, 21]                    
 [74, 513, 166, 340, 226, 121]                       
 [74, 513, 166, 340, 226, 218, 459]                  
 [74, 513, 116, 121, 340]                            
 [74, 513, 268, 218, 459, 222]                       
 [74, 513, 268, 218, 459, 340]                       
 [74, 764, 314]                                      
 [74, 764, 331]                                      
 ⋮                                                   
 [6, 4, 252, 58, 63, 183, 520, 286, 137, 281, 285]   
 [6, 4, 252, 58, 63, 183, 520, 286, 137, 281, 3, 859]
 [6, 4, 252, 58, 63, 183, 520, 89, 285]              
 [6, 426, 168, 458, 285, 486, 183]         